drop database if exists eVolitve;
create database eVolitve;
use eVolitve;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS DRZAVLJANI (
    EMSO BIGINT(13) NOT NULL,
    IME VARCHAR(255) COLLATE utf8_slovenian_ci NOT NULL,
    PRIIMEK VARCHAR(255) COLLATE utf8_slovenian_ci NOT NULL,
    KRAJ VARCHAR(255) COLLATE utf8_slovenian_ci NOT NULL,
    GESLO VARCHAR(255) COLLATE utf8_slovenian_ci NOT NULL,
    SOGLASJE BOOLEAN NOT NULL,
    PRIMARY KEY (EMSO)
 ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_slovenian_ci;

CREATE TABLE IF NOT EXISTS STRANKE (
    ID_STRANKE INT(2) NOT NULL AUTO_INCREMENT,
    NAZIV_STRANKE VARCHAR(255) COLLATE utf8_slovenian_ci NOT NULL,
    OPIS1 LONGTEXT COLLATE utf8_slovenian_ci NOT NULL,
    OPIS2 LONGTEXT COLLATE utf8_slovenian_ci NOT NULL,
    PREDSEDNIK VARCHAR(255) COLLATE utf8_slovenian_ci NOT NULL,
    LINK VARCHAR(255) COLLATE utf8_slovenian_ci NOT NULL,
    PATH_IMAGE1 VARCHAR(255) NOT NULL, /*SLIKA LOGO STRANKE*/
    PATH_IMAGE2 VARCHAR(255) NOT NULL, /*SLIKA PREDSTAVNIKA*/
    PRIMARY KEY (ID_STRANKE)
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_slovenian_ci;

CREATE TABLE IF NOT EXISTS PREDSTAVNIKI (
    ID_KRAJ INT(3) NOT NULL AUTO_INCREMENT,
    ID_STRANKE INT(2) NOT NULL,
    KRAJ VARCHAR(255) NOT NULL,
    IME_PREDSTAVNIK VARCHAR(255) NOT NULL,
    PATH_IMAGE_PREDSTAVNIK VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_KRAJ),
    FOREIGN KEY (ID_STRANKE) REFERENCES STRANKE(ID_STRANKE)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_slovenian_ci;

CREATE TABLE IF NOT EXISTS GLASOVI (
    EMSO INT(13) NOT NULL,
    ID_STRANKE INT(2) NOT NULL,
    PRIMARY KEY (EMSO),
    FOREIGN KEY (ID_STRANKE) REFERENCES STRANKE(ID_STRANKE)
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_slovenian_ci;